import type {
  CheckInDraft,
  CircleDetailModel,
  CreateCircleDraft,
  TodayCircleCard,
  UserProfile,
} from '../../types/models';
import {avatarImages} from '../../assets/avatars';

export const initialCheckInDraft: CheckInDraft = {
  note: '',
};

export const initialCreateCircleDraft: CreateCircleDraft = {
  category: 'Fitness',
  title: 'Fitness Fanatics',
  dailyTask: '30min workout',
  privacy: 'public',
  maxSize: 8,
  inviteCode: 'hoyst.app/join/vanguard-832',
};

export const currentUserProfile: UserProfile = {
  id: 'u-kelvin',
  handle: 'kelvin',
  name: 'Kelvin',
  avatarImage: avatarImages.kelvin,
  bio: 'Builder. Accountable. Quietly competitive.',
  timezone: 'America/New_York',
};

export const todayCircles: TodayCircleCard[] = [
  {
    id: 'fitness-fanatics',
    title: 'Fitness Fanatics',
    category: 'Fitness',
    dailyTask: '30min workout',
    state: 'active',
    progressPercent: 75,
    viewerHasCheckedIn: true,
    remainingCheckIns: 2,
    streakDays: 12,
    streakLabel: '12-day group streak',
    members: [
      {
        id: 'm1',
        name: 'Kelvin',
        initials: 'KE',
        avatarImage: avatarImages.kelvin,
        state: 'done',
        badgeCount: 12,
      },
      {
        id: 'm2',
        name: 'Ava',
        initials: 'AV',
        avatarImage: avatarImages.ava,
        state: 'done',
        badgeCount: 8,
      },
      {
        id: 'm3',
        name: 'Marcus',
        initials: 'MA',
        avatarImage: avatarImages.marcus,
        state: 'pending',
        badgeCount: 15,
      },
      {
        id: 'm4',
        name: 'Theo',
        initials: 'TH',
        avatarImage: avatarImages.theo,
        state: 'missed',
        badgeCount: 3,
      },
    ],
  },
  {
    id: 'mindful-mornings',
    title: 'Mindful Mornings',
    category: 'Wellness',
    dailyTask: '10min meditation',
    state: 'done',
    progressPercent: 100,
    viewerHasCheckedIn: true,
    remainingCheckIns: 0,
    streakDays: 45,
    streakLabel: '45d streak',
    members: [
      {
        id: 'm5',
        name: 'Nina',
        initials: 'NI',
        avatarImage: avatarImages.nina,
        state: 'done',
        badgeCount: 5,
      },
      {
        id: 'm6',
        name: 'Rory',
        initials: 'RO',
        avatarImage: avatarImages.rory,
        state: 'done',
        badgeCount: 2,
      },
    ],
    completionLabel: 'Daily Log Complete',
  },
  {
    id: 'sober-squad',
    title: 'Sober Squad',
    category: 'Sobriety',
    dailyTask: 'Daily sobriety check-in',
    state: 'risk',
    progressPercent: 42,
    viewerHasCheckedIn: false,
    remainingCheckIns: 2,
    streakDays: 7,
    streakLabel: '7-day streak',
    members: [
      {
        id: 'm7',
        name: 'Lia',
        initials: 'LI',
        avatarImage: avatarImages.lia,
        state: 'done',
        badgeCount: 4,
      },
      {
        id: 'm8',
        name: 'Noah',
        initials: 'NO',
        avatarImage: avatarImages.noah,
        state: 'pending',
        badgeCount: 7,
      },
      {
        id: 'm9',
        name: 'Zoe',
        initials: 'ZO',
        avatarImage: avatarImages.zoe,
        state: 'pending',
        badgeCount: 1,
      },
    ],
    progressLabel: 'Need 2 more today',
  },
];

export const circleDetails: Record<string, CircleDetailModel> = {
  'fitness-fanatics': {
    id: 'fitness-fanatics',
    category: 'Fitness',
    streakLabel: '12d streak',
    title: 'Fitness Fanatics',
    dailyGoal: 'Daily goal: 30min workout',
    completionRate: 82,
    members: [
      {
        id: 'm1',
        name: 'Kelvin',
        initials: 'KE',
        avatarImage: avatarImages.kelvin,
        state: 'done',
        badgeCount: 12,
      },
      {
        id: 'm2',
        name: 'Ava',
        initials: 'AV',
        avatarImage: avatarImages.ava,
        state: 'pending',
        badgeCount: 8,
      },
      {
        id: 'm3',
        name: 'Marcus',
        initials: 'MA',
        avatarImage: avatarImages.marcus,
        state: 'done',
        badgeCount: 15,
      },
      {
        id: 'm4',
        name: 'Theo',
        initials: 'TH',
        avatarImage: avatarImages.theo,
        state: 'missed',
        badgeCount: 3,
      },
    ],
    monthProgress: [
      {day: 1, state: 'done'},
      {day: 2, state: 'done'},
      {day: 3, state: 'missed'},
      {day: 4, state: 'done'},
      {day: 5, state: 'done'},
      {day: 6, state: 'done'},
      {day: 7, state: 'future'},
      {day: 8, state: 'done'},
      {day: 9, state: 'done'},
      {day: 10, state: 'done'},
      {day: 11, state: 'done'},
      {day: 12, state: 'done'},
      {day: 13, state: 'today'},
      {day: 14, state: 'future'},
    ],
    activity: [
      {
        id: 'a1',
        actorName: 'Ava',
        actorInitials: 'AV',
        actorAvatarImage: avatarImages.ava,
        tone: 'success',
        message: 'completed her 30min workout',
        timestamp: '2 hours ago',
        imageVariant: 'workout',
      },
      {
        id: 'a2',
        actorName: 'Marcus',
        actorInitials: 'MA',
        actorAvatarImage: avatarImages.marcus,
        tone: 'pending',
        message: 'is Pending. Poke him?',
        timestamp: '5 hours ago',
        actionLabel: 'Poke',
      },
    ],
  },
  'mindful-mornings': {
    id: 'mindful-mornings',
    category: 'Wellness',
    streakLabel: '45d streak',
    title: 'Mindful Mornings',
    dailyGoal: 'Daily goal: 10min meditation',
    completionRate: 91,
    members: [
      {
        id: 'w1',
        name: 'June',
        initials: 'JU',
        avatarImage: avatarImages.june,
        state: 'done',
        badgeCount: 6,
      },
      {
        id: 'w2',
        name: 'Mia',
        initials: 'MI',
        avatarImage: avatarImages.mia,
        state: 'done',
        badgeCount: 7,
      },
      {
        id: 'w3',
        name: 'Kai',
        initials: 'KA',
        avatarImage: avatarImages.kai,
        state: 'pending',
        badgeCount: 2,
      },
    ],
    monthProgress: [
      {day: 1, state: 'done'},
      {day: 2, state: 'done'},
      {day: 3, state: 'done'},
      {day: 4, state: 'done'},
      {day: 5, state: 'done'},
      {day: 6, state: 'done'},
      {day: 7, state: 'done'},
      {day: 8, state: 'done'},
      {day: 9, state: 'done'},
      {day: 10, state: 'done'},
      {day: 11, state: 'done'},
      {day: 12, state: 'done'},
      {day: 13, state: 'today'},
      {day: 14, state: 'future'},
    ],
    activity: [
      {
        id: 'b1',
        actorName: 'June',
        actorInitials: 'JU',
        actorAvatarImage: avatarImages.june,
        tone: 'success',
        message: 'logged a quiet morning reset',
        timestamp: '1 hour ago',
      },
    ],
  },
  'sober-squad': {
    id: 'sober-squad',
    category: 'Sobriety',
    streakLabel: '7-day streak',
    title: 'Sober Squad',
    dailyGoal: 'Daily goal: sobriety check-in',
    completionRate: 67,
    members: [
      {
        id: 's1',
        name: 'Lia',
        initials: 'LI',
        avatarImage: avatarImages.lia,
        state: 'done',
        badgeCount: 4,
      },
      {
        id: 's2',
        name: 'Noah',
        initials: 'NO',
        avatarImage: avatarImages.noah,
        state: 'pending',
        badgeCount: 7,
      },
      {
        id: 's3',
        name: 'Zoe',
        initials: 'ZO',
        avatarImage: avatarImages.zoe,
        state: 'pending',
        badgeCount: 1,
      },
    ],
    monthProgress: [
      {day: 1, state: 'done'},
      {day: 2, state: 'missed'},
      {day: 3, state: 'done'},
      {day: 4, state: 'done'},
      {day: 5, state: 'missed'},
      {day: 6, state: 'done'},
      {day: 7, state: 'done'},
      {day: 8, state: 'done'},
      {day: 9, state: 'done'},
      {day: 10, state: 'done'},
      {day: 11, state: 'future'},
      {day: 12, state: 'future'},
      {day: 13, state: 'today'},
      {day: 14, state: 'future'},
    ],
    activity: [
      {
        id: 'c1',
        actorName: 'Lia',
        actorInitials: 'LI',
        actorAvatarImage: avatarImages.lia,
        tone: 'success',
        message: 'checked in and kept the streak alive',
        timestamp: '38 minutes ago',
      },
      {
        id: 'c2',
        actorName: 'Noah',
        actorInitials: 'NO',
        actorAvatarImage: avatarImages.noah,
        tone: 'alert',
        message: 'has not checked in yet',
        timestamp: '4 hours ago',
        actionLabel: 'Poke',
      },
    ],
  },
};

export function getCircleDetail(circleId: string): CircleDetailModel {
  return circleDetails[circleId] ?? circleDetails['fitness-fanatics'];
}
