export const typography = {
  hero: {
    fontSize: 52,
    lineHeight: 56,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  display: {
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  largeTitle: {
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  headline: {
    fontSize: 32,
    lineHeight: 36,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  title: {
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  subtitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  body: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500' as const,
    letterSpacing: 0,
  },
  bodyStrong: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  label: {
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800' as const,
    letterSpacing: 0.6,
    textTransform: 'uppercase' as const,
  },
  caption: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600' as const,
    letterSpacing: 0,
  },
  tiny: {
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '700' as const,
    letterSpacing: 0.4,
    textTransform: 'uppercase' as const,
  },
  button: {
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
  navLabel: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800' as const,
    letterSpacing: 0,
  },
} as const;
